/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.desktop.tela;

import br.edu.agenda.visao.AgendaVisao;
import br.edu.biblia.tela.TelaEscolherLivro;
import br.edu.calculadora.telas.TelaCalculadora;
import br.edu.desktop.widgets.calendario.WidgetCalendario;
import br.edu.desktop.widgets.clima.WidgetClima;
import br.edu.desktop.widgets.relogio.WidgetRelogio;
import br.edu.flappybird.views.JanelaJogo;
import br.edu.jogodavelha.tela.JogoDaVelha;
import br.edu.login.tela.TelaLogin;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Image;
import java.awt.Color;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

public class Desktop extends javax.swing.JFrame {
    private Image fundo;
    /**
     * Creates new form Desktop
     */
    public Desktop() {
        System.setProperty("flatlaf.menuBarEmbedded", "true");
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_SHOW_ICON, false);
        
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/br/edu/desktop/img/chmaior.png")).getImage());
        
        try {
            fundo = ImageIO.read(Desktop.class.getResourceAsStream("/br/edu/desktop/img/fundo.jpg"));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        jLabel2.setIcon(new ImageIcon(fundo.getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH)));
        
        // Adicionando os widgets
        WidgetClima clima = new WidgetClima();
        jpnTela.add(clima, new AbsoluteConstraints(370, 306, 222, 80), 2);
        
        WidgetRelogio relog = new WidgetRelogio();
        jpnTela.add(relog, new AbsoluteConstraints(370, 190, 106, 106), 2);
        
        WidgetCalendario calen = new WidgetCalendario();
        jpnTela.add(calen, new AbsoluteConstraints(486, 190, 106, 106), 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTela = new javax.swing.JPanel();
        techoslogo = new javax.swing.JLabel();
        jpnTaskbar = new javax.swing.JPanel();
        jlCalculadora = new javax.swing.JLabel();
        jlJogoVelha = new javax.swing.JLabel();
        jlAgenda = new javax.swing.JLabel();
        jlFlappy = new javax.swing.JLabel();
        jlBiblia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpnTela.setForeground(new java.awt.Color(0, 153, 255));
        jpnTela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpnTela.setBackground(new Color(0, 0, 0, 0));

        techoslogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/desktop/img/techos.png"))); // NOI18N
        jpnTela.add(techoslogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 280, 110));

        jpnTaskbar.setOpaque(false);
        jpnTaskbar.setBackground(new Color(51,51,51, 220));

        jlCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/desktop/img/calculadora.png"))); // NOI18N
        jlCalculadora.setToolTipText("Calculadora");
        jlCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCalculadoraMouseClicked(evt);
            }
        });

        jlJogoVelha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/desktop/img/jogodavelha.png"))); // NOI18N
        jlJogoVelha.setToolTipText("Jogo da Velha");
        jlJogoVelha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlJogoVelhaMouseClicked(evt);
            }
        });

        jlAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/desktop/img/contatos.png"))); // NOI18N
        jlAgenda.setToolTipText("Agenda de Contatos");
        jlAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAgendaMouseClicked(evt);
            }
        });

        jlFlappy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/desktop/img/flappy.png"))); // NOI18N
        jlFlappy.setToolTipText("Flappy Bird");
        jlFlappy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlFlappyMouseClicked(evt);
            }
        });

        jlBiblia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/desktop/img/biblia.png"))); // NOI18N
        jlBiblia.setToolTipText("Bíblia Sagrada");
        jlBiblia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBibliaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnTaskbarLayout = new javax.swing.GroupLayout(jpnTaskbar);
        jpnTaskbar.setLayout(jpnTaskbarLayout);
        jpnTaskbarLayout.setHorizontalGroup(
            jpnTaskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTaskbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlAgenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlCalculadora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlFlappy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlBiblia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlJogoVelha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTaskbarLayout.setVerticalGroup(
            jpnTaskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTaskbarLayout.createSequentialGroup()
                .addGroup(jpnTaskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCalculadora)
                    .addGroup(jpnTaskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlFlappy, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlAgenda, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpnTaskbarLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(jpnTaskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlJogoVelha)
                                .addComponent(jlBiblia)))))
                .addGap(12, 12, 12))
        );

        jpnTaskbar.putClientProperty(FlatClientProperties.STYLE, "arc: 35");

        jpnTela.add(jpnTaskbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 390, -1));

        jLabel2.setMaximumSize(new java.awt.Dimension(940, 550));
        jLabel2.setMinimumSize(new java.awt.Dimension(940, 550));
        jLabel2.setPreferredSize(new java.awt.Dimension(940, 550));
        jpnTela.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 550));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/desktop/img/ch.png"))); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/desktop/img/lua-crescente.png"))); // NOI18N
        jMenuItem1.setText("Bloquear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/desktop/img/ligar.png"))); // NOI18N
        jMenuItem2.setText("Desligar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SobreFrame dialog2 = new SobreFrame(this, true);
        dialog2.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(this, "Até mais!");
        
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jlFlappyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFlappyMouseClicked
        JanelaJogo flappy = new JanelaJogo();
        flappy.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jlFlappyMouseClicked

    private void jlAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAgendaMouseClicked
        AgendaVisao agenda = new AgendaVisao();
        agenda.setVisible(true);
        agenda.redimensionarFundo();
        
        this.dispose();
    }//GEN-LAST:event_jlAgendaMouseClicked

    private void jlJogoVelhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlJogoVelhaMouseClicked
        JogoDaVelha jv = new JogoDaVelha();
        jv.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jlJogoVelhaMouseClicked

    private void jlBibliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBibliaMouseClicked
        TelaEscolherLivro tel = new TelaEscolherLivro();
        tel.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jlBibliaMouseClicked

    private void jlCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCalculadoraMouseClicked
        TelaCalculadora telc = new TelaCalculadora();
        telc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlCalculadoraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel jlAgenda;
    private javax.swing.JLabel jlBiblia;
    private javax.swing.JLabel jlCalculadora;
    private javax.swing.JLabel jlFlappy;
    private javax.swing.JLabel jlJogoVelha;
    private javax.swing.JPanel jpnTaskbar;
    private javax.swing.JPanel jpnTela;
    private javax.swing.JLabel techoslogo;
    // End of variables declaration//GEN-END:variables
}
