package br.edu.flappybird.views;

import br.edu.desktop.tela.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import br.edu.flappybird.jogo.Jogo;
import br.edu.util.FuncoesUteis;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.ui.FlatRoundBorder;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Font;
import java.awt.Point;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author gabri
 */
public class JanelaJogo extends javax.swing.JFrame implements KeyListener {
    private Jogo jogo;
    
    private Timer animTremerTempo;
    private Timer animPararTremerTempo;
    private Timer animAparecerMenuTempo;
    private Timer animFundo;
    
    /**
     * Creates new form Jogo
     */
    public JanelaJogo() {
        //getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_SHOW_ICON, false);
        
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/br/edu/desktop/img/flappy.png")).getImage());
        
        jogo = new Jogo(this);
        
        setLocationRelativeTo(null);
        
        jogoPainel.setLayout(null);
        tecladoTF.addKeyListener(this);
        
        tecladoTF.requestFocus();
        
        setTextoGameOverVisivel(false, 0);
        
        Font f = FuncoesUteis.carregarFonte("/br/edu/flappybird/fonts/Golden Age Shad.ttf").deriveFont(Font.PLAIN, 36);
        if (f != null) pontuacaolbl.setFont(f);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnMenu = new javax.swing.JPanel();
        jlPontMenu = new javax.swing.JLabel();
        jlAhNao = new javax.swing.JLabel();
        jltitlemenu = new javax.swing.JLabel();
        btnJogar = new javax.swing.JButton();
        btnComoJogar = new javax.swing.JButton();
        jlFundomenu = new javax.swing.JLabel();
        jogoPainel = new javax.swing.JPanel();
        jpPontuacao = new javax.swing.JPanel();
        pontuacaolbl = new javax.swing.JLabel();
        passarinholbl = new javax.swing.JLabel();
        tecladoTF = new javax.swing.JTextField();
        cenariolbl = new javax.swing.JLabel();
        cenariolblaux = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuNovoJogo = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuComoJogar = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Flappy Bird");
        setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        setLocation(new java.awt.Point(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jpnMenu.setLayout(null);

        jlPontMenu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlPontMenu.setForeground(new java.awt.Color(255, 255, 255));
        jlPontMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPontMenu.setText("Sua pontuação foi: ");
        jpnMenu.add(jlPontMenu);
        jlPontMenu.setBounds(0, 230, 500, 30);

        jlAhNao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlAhNao.setForeground(new java.awt.Color(255, 255, 255));
        jlAhNao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAhNao.setText("Ah não! Você perdeu!");
        jpnMenu.add(jlAhNao);
        jlAhNao.setBounds(0, 200, 500, 30);

        jltitlemenu.setFont(new java.awt.Font("Arial", 1, 56)); // NOI18N
        jltitlemenu.setForeground(new java.awt.Color(255, 255, 255));
        jltitlemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitlemenu.setText("Flappy Bird");
        jpnMenu.add(jltitlemenu);
        jltitlemenu.setBounds(0, 30, 500, 180);

        btnJogar.putClientProperty(FlatClientProperties.STYLE, "arc:999; hoverBackground: #53D253");
        btnJogar.setBackground(new java.awt.Color(102, 255, 102));
        btnJogar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnJogar.setForeground(new java.awt.Color(21, 54, 21));
        btnJogar.setText("Jogar");
        btnJogar.setFocusPainted(false);
        btnJogar.setRequestFocusEnabled(false);
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });
        jpnMenu.add(btnJogar);
        btnJogar.setBounds(180, 280, 146, 46);

        btnComoJogar.putClientProperty(FlatClientProperties.STYLE, "arc: 999; hoverBackground: #D2D254");
        btnComoJogar.setBackground(new java.awt.Color(255, 255, 102));
        btnComoJogar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnComoJogar.setForeground(new java.awt.Color(54, 54, 21));
        btnComoJogar.setText("Como Jogar?");
        btnComoJogar.setFocusPainted(false);
        btnComoJogar.setPreferredSize(new java.awt.Dimension(146, 46));
        btnComoJogar.setRequestFocusEnabled(false);
        btnComoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComoJogarActionPerformed(evt);
            }
        });
        jpnMenu.add(btnComoJogar);
        btnComoJogar.setBounds(180, 350, 146, 46);

        jlFundomenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/flappybird/imagens/fundomenu.png"))); // NOI18N
        jlFundomenu.setText("jLabel1");
        jpnMenu.add(jlFundomenu);
        jlFundomenu.setBounds(0, 0, 500, 500);

        getContentPane().add(jpnMenu);
        jpnMenu.setBounds(0, 0, 500, 480);

        jogoPainel.setMaximumSize(new java.awt.Dimension(500, 500));
        jogoPainel.setMinimumSize(new java.awt.Dimension(500, 500));
        jogoPainel.setPreferredSize(new java.awt.Dimension(500, 500));
        jogoPainel.setLayout(null);

        jpPontuacao.setOpaque(false);
        jpPontuacao.setLayout(new java.awt.BorderLayout());
        FlatRoundBorder jpPontuacaoBorder = new FlatRoundBorder();
        jpPontuacaoBorder.applyStyleProperty("arc", 999);
        jpPontuacaoBorder.applyStyleProperty("borderWidth", 5);
        jpPontuacaoBorder.applyStyleProperty("borderColor", new Color(0,0,0));

        jpPontuacao.putClientProperty(FlatClientProperties.STYLE, "arc: 999; background: #fff");

        jpPontuacao.setBorder(jpPontuacaoBorder);

        pontuacaolbl.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        pontuacaolbl.setForeground(new java.awt.Color(0, 0, 0));
        pontuacaolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pontuacaolbl.setText("0");
        pontuacaolbl.setFocusable(false);
        pontuacaolbl.setRequestFocusEnabled(false);
        pontuacaolbl.setVerifyInputWhenFocusTarget(false);
        jpPontuacao.add(pontuacaolbl, java.awt.BorderLayout.CENTER);

        jogoPainel.add(jpPontuacao);
        jpPontuacao.setBounds(190, 10, 130, 60);

        passarinholbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/flappybird/imagens/passarinho4k.png"))); // NOI18N
        passarinholbl.setMaximumSize(new java.awt.Dimension(100, 100));
        passarinholbl.setMinimumSize(new java.awt.Dimension(100, 100));
        passarinholbl.setPreferredSize(new java.awt.Dimension(100, 100));
        jogoPainel.add(passarinholbl);
        passarinholbl.setBounds(10, 360, 120, 80);

        tecladoTF.setFocusAccelerator(' ');
        jogoPainel.add(tecladoTF);
        tecladoTF.setBounds(601, 0, 4, 2);

        cenariolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/flappybird/imagens/cenario.png"))); // NOI18N
        jogoPainel.add(cenariolbl);
        cenariolbl.setBounds(0, 0, 667, 500);

        cenariolblaux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/flappybird/imagens/cenario.png"))); // NOI18N
        jogoPainel.add(cenariolblaux);
        cenariolblaux.setBounds(667, 0, 667, 500);

        getContentPane().add(jogoPainel);
        jogoPainel.setBounds(0, 0, 500, 477);

        jMenu2.setText("Jogo");

        menuNovoJogo.setText("Novo Jogo");
        menuNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoJogoActionPerformed(evt);
            }
        });
        jMenu2.add(menuNovoJogo);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu2.add(menuSair);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        menuComoJogar.setText("Como jogar?");
        menuComoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComoJogarActionPerformed(evt);
            }
        });
        jMenu3.add(menuComoJogar);

        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        jMenu3.add(menuSobre);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Botão Sair do Menu Bar
    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        new Desktop().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_menuSairActionPerformed

    // Botão Novo Jogo do Menu Bar
    private void menuNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoJogoActionPerformed

        jogo.iniciarJogo();
    }//GEN-LAST:event_menuNovoJogoActionPerformed

    // Botão Como Jogar do Menu Bar
    private void menuComoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuComoJogarActionPerformed
        JanelaComoJogar d = new JanelaComoJogar(this, true);
        
        d.centralizarTela();
        
        d.setVisible(true);
    }//GEN-LAST:event_menuComoJogarActionPerformed

    // Botão Sobre do Menu Bar
    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        JanelaSobre d = new JanelaSobre(this, true);
        
        d.setVisible(true);
    }//GEN-LAST:event_menuSobreActionPerformed

    // Botão Como Jogar do painel Menu
    private void btnComoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComoJogarActionPerformed
        JanelaComoJogar d = new JanelaComoJogar(this, true);

        d.setVisible(true);
    }//GEN-LAST:event_btnComoJogarActionPerformed

    // Botão Jogar do painel Menu
    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        jogo.iniciarJogo();
    }//GEN-LAST:event_btnJogarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Desktop().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    public Jogo getJogo() {
        return jogo;
    }
    
    public void setJogo(Jogo j) {
        jogo = j;
    }
    
    public void setMenuVisivel(boolean visibilidade) {
        jpnMenu.setVisible(visibilidade);
        jogoPainel.setVisible(!visibilidade);
    }
    
    public void setTextoGameOverVisivel(boolean visibilidade, int pontuacao) {
        jlPontMenu.setText("Sua pontuação foi: " + pontuacao);
        jlAhNao.setVisible(visibilidade);
        jlPontMenu.setVisible(visibilidade);
    }
    
    public void tremerTela(int milli, int tempoAntesDoMenu) {
        animTremerTempo = new Timer(50, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int tremerMax = 4;
                int tremerMin = -6;
                
                Random random = new Random();
                int x = random.nextInt(tremerMax - tremerMin) + tremerMin;
                int y = random.nextInt(tremerMax - tremerMin) + tremerMin;
                
                jogoPainel.setLocation(x, y);
            }
        });
        
        animPararTremerTempo = new Timer(milli, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                animPararTremerTempo.stop();
                animTremerTempo.stop();
                
                jogoPainel.setLocation(0,0);
                animAparecerMenuTempo.start();
            }
        });
        
        animAparecerMenuTempo = new Timer(tempoAntesDoMenu, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                animAparecerMenuTempo.stop();
                
                jogo.gameOver(false);
            }
        });
        
        animTremerTempo.start();
        animPararTremerTempo.start();
    }
    
    public void ativarParallax() {
        animFundo = new Timer(60, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Point loc = cenariolbl.getLocation();
                Point auxloc = cenariolblaux.getLocation();
                
                cenariolbl.setLocation(loc.x - 1, loc.y);
                cenariolblaux.setLocation(auxloc.x - 1, auxloc.y);
                
                if (loc.x <= -666) {
                    cenariolbl.setLocation(667,0);
                } else if (auxloc.x <= -666) {
                    cenariolblaux.setLocation(667,0);
                }
            }
        });
        
        animFundo.start();
    }
    
    public void desativarParallax(boolean reset) {
        if (animFundo != null) animFundo.stop();
        
        if (reset) {
            cenariolbl.setLocation(0,0);
            cenariolblaux.setLocation(667, 0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnComoJogar;
    public javax.swing.JButton btnJogar;
    private javax.swing.JLabel cenariolbl;
    private javax.swing.JLabel cenariolblaux;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jlAhNao;
    private javax.swing.JLabel jlFundomenu;
    private javax.swing.JLabel jlPontMenu;
    private javax.swing.JLabel jltitlemenu;
    public javax.swing.JPanel jogoPainel;
    private javax.swing.JPanel jpPontuacao;
    public javax.swing.JPanel jpnMenu;
    private javax.swing.JMenuItem menuComoJogar;
    private javax.swing.JMenuItem menuNovoJogo;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuSobre;
    public javax.swing.JLabel passarinholbl;
    public javax.swing.JLabel pontuacaolbl;
    public javax.swing.JTextField tecladoTF;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
        // O código 32 refere-se a tecla ESPAÇO
        if (e.getKeyCode() == KeyEvent.VK_SPACE) {
            if (jogo.getJogoAtivo()) jogo.getPassaro().pular();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        
    }
}
