/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.flappybird.views;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JFrame;
import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author Kaua Sousa
 */
public class JanelaComoJogar extends JDialog {

    /**
     * Creates new form JanelaComoJogar
     */
    public JanelaComoJogar(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnJogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Como jogar?");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(450, 300));
        setMinimumSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(450, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 300));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html><p>O objetivo do jogo é atravessar os canos para obter a melhor pontuação possível.</p><br><p>Aperte a barra de espaço do seu teclado para fazer o pássaro voar!</p></html>");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 200));
        jLabel1.setMinimumSize(new java.awt.Dimension(300, 200));
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel1.add(jLabel1);

        btnJogar.putClientProperty(FlatClientProperties.STYLE, "arc: 999; hoverBackground: #D2D254");
        btnJogar.setBackground(new java.awt.Color(255, 255, 102));
        btnJogar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnJogar.setForeground(new java.awt.Color(115, 115, 46));
        btnJogar.setText("OK");
        btnJogar.setAlignmentX(0.5F);
        btnJogar.setFocusPainted(false);
        btnJogar.setMaximumSize(new java.awt.Dimension(146, 46));
        btnJogar.setMinimumSize(new java.awt.Dimension(146, 46));
        btnJogar.setPreferredSize(new java.awt.Dimension(146, 46));
        btnJogar.setRequestFocusEnabled(false);
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });
        jPanel1.add(btnJogar);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnJogarActionPerformed

    public void centralizarTela() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int w = (int)screenSize.getWidth();
        int h = (int)screenSize.getHeight();

        setLocation(
            (w / 2) - (getWidth()  / 2),
            (h / 2) - (getHeight() / 2)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnJogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
