/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.desktop.widgets.calendario;

import br.edu.util.FuncoesUteis;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Font;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Kaua Sousa
 */
public class WidgetCalendario extends javax.swing.JPanel {
    Font sf18;
    Font sf52;
    
    /**
     * Creates new form WidgetCalendario
     */
    public WidgetCalendario() {
        initComponents();
        
        putClientProperty(FlatClientProperties.STYLE, "arc: 35");
        
        Font sf = FuncoesUteis.carregarFonte("/br/edu/desktop/fonts/SF-Pro-Display-Bold.otf");
        sf18 = sf.deriveFont(Font.PLAIN, 18);
        sf52 = sf.deriveFont(Font.PLAIN, 56);
        
        jlMes.setFont(sf18);
        jlDiaSemana.setFont(sf18);
        jlDia.setFont(sf52);
        
        LocalDateTime data = LocalDateTime.now();
        String diaSemana = DateTimeFormatter.ofPattern("E").format(data);
        // Colocando a primeira letra como maiúscula, assim  como é no MacOS.
        diaSemana = diaSemana.substring(0, 1).toUpperCase() + diaSemana.substring(1);
        String mes = DateTimeFormatter.ofPattern("LLL").format(data);
        String dia = DateTimeFormatter.ofPattern("d").format(data);
        
        jlDiaSemana.setText(diaSemana);
        jlMes.setText(mes);
        jlDia.setText(dia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlDiaSemana = new javax.swing.JLabel();
        jlMes = new javax.swing.JLabel();
        jlDia = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(106, 106));
        setPreferredSize(new java.awt.Dimension(106, 106));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlDiaSemana.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlDiaSemana.setForeground(new java.awt.Color(217, 58, 49));
        jlDiaSemana.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlDiaSemana.setText("Sáb.");
        add(jlDiaSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 52, 30));

        jlMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlMes.setForeground(new java.awt.Color(115, 115, 115));
        jlMes.setText("out.");
        add(jlMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 10, 50, 30));

        jlDia.setFont(new java.awt.Font("Segoe UI", 0, 56)); // NOI18N
        jlDia.setForeground(new java.awt.Color(35, 35, 35));
        jlDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDia.setText("24");
        jlDia.setToolTipText("");
        jlDia.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jlDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 106, 70));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlDia;
    private javax.swing.JLabel jlDiaSemana;
    private javax.swing.JLabel jlMes;
    // End of variables declaration//GEN-END:variables
}
