/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.desktop.widgets.relogio;

import br.edu.util.FuncoesUteis;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

/**
 *
 * @author Kaua Sousa
 */
public class WidgetRelogio extends javax.swing.JPanel {
    Timer horarioAutomatico;
    Font sf56;
    Font sf48;
    DateTimeFormatter formatadorData;
    
    /**
     * Creates new form WidgetRelogio
     */
    public WidgetRelogio() {
        initComponents();
        
        putClientProperty(FlatClientProperties.STYLE, "arc: 35");
        
        Font sf = FuncoesUteis.carregarFonte("/br/edu/desktop/fonts/sf-ns-compressed-bold.ttf");
        sf56 = sf.deriveFont(Font.PLAIN, 56);
        sf48 = sf.deriveFont(Font.PLAIN, 48);
        
        jLabel1.setFont(sf56);
        
        formatadorData = DateTimeFormatter.ofPattern("H:mm");
        
        atualizarHorario();
        
        // Mudando o horário a cada 1 segundo.
        horarioAutomatico = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                atualizarHorario();
            }
        });
        
        horarioAutomatico.start();
    }
    
    public void atualizarHorario () {
        LocalDateTime data = LocalDateTime.now();
                
        String novoTitulo = formatadorData.format(data);
                
        if (novoTitulo.length() > 4) {
            jLabel1.setFont(sf48);
        } else {
            jLabel1.setFont(sf56);
        }
            
        jLabel1.setText(novoTitulo);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(106, 106));
        setPreferredSize(new java.awt.Dimension(106, 106));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("9:41");
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
