/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.biblia.tela;

import br.edu.biblia.dao.BibliaDao;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.text.View;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author gabri
 */
public class TelaLer extends JFrame {

    int[] qtdCap = {
        50,  // Gênesis
        40,  // Êxodo
        27,  // Levítico
        36,  // Números
        34,  // Deuteronômio
        24,  // Josué
        21,  // Juízes
        4,   // Rute
        31,  // 1 Samuel
        24,  // 2 Samuel
        22,  // 1 Reis
        25,  // 2 Reis
        29,  // 1 Crônicas
        36,  // 2 Crônicas
        10,  // Esdras
        13,  // Neemias
        10,  // Ester
        42,  // Jó
        150, // Salmos
        31,  // Provérbios
        12,  // Eclesiastes
        8,   // Cantares de Salomão
        66,  // Isaías
        52,  // Jeremias
        5,   // Lamentações
        48,  // Ezequiel
        12,  // Daniel
        14,  // Oséias
        3,   // Joel
        9,   // Amós
        1,   // Obadias
        4,   // Jonas
        7,   // Miqueias
        3,   // Naum
        3,   // Habacuque
        3,   // Sofonias
        2,   // Ageu
        14,  // Zacarias
        4,   // Malaquias
        28,  // Mateus
        16,  // Marcos
        24,  // Lucas
        21,  // João
        28,  // Atos
        16,  // Romanos
        16,  // 1 Coríntios
        13,  // 2 Coríntios
        6,   // Gálatas
        6,   // Efésios
        4,   // Filipenses
        4,   // Colossenses
        5,   // 1 Tessalonicenses
        3,   // 2 Tessalonicenses
        6,   // 1 Timóteo
        4,   // 2 Timóteo
        3,   // Tito
        1,   // Filemom
        13,  // Hebreus
        5,   // Tiago
        5,   // 1 Pedro
        3,   // 2 Pedro
        5,   // 1 João
        1,   // 2 João
        1,   // 3 João
        1,   // Judas
        22   // Apocalipse
    };

    BibliaDao dao = new BibliaDao();
    
    private int livro;
    private int capitulo;
    
    /**
     * Creates new form BibliaSagrada
     */
    public TelaLer(int livro, int capitulo) {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/br/edu/biblia/imagens/biblia.png")).getImage());
        
        this.livro = livro;
        this.capitulo = capitulo;
        
        try {
            jlLivro.setText(dao.consultarLivro(livro));
            jlCapitulo.setText(""+capitulo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        carregarCapitulo(capitulo);
        
        // Velocidade do scroll.
        JScrollBar verticalScrollBar = jScrollPane1.getVerticalScrollBar();
        verticalScrollBar.setUnitIncrement(16);
        verticalScrollBar.setBlockIncrement(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        versiculos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlLivro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlCapitulo = new javax.swing.JLabel();
        jbPassarCapitulo = new javax.swing.JButton();
        jbVoltarCapitulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bíblia Sagrada");
        setMinimumSize(new java.awt.Dimension(490, 670));
        setResizable(false);
        setSize(new java.awt.Dimension(490, 670));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setPreferredSize(new java.awt.Dimension(458, 668));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        versiculos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(versiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 420, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Capítulo:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 80, -1));

        jlLivro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlLivro.setText("livro");
        jPanel2.add(jlLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Livro:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, -1));

        jlCapitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlCapitulo.setText("123");
        jPanel2.add(jlCapitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jbPassarCapitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/biblia/imagens/right-arrow.png"))); // NOI18N
        jbPassarCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPassarCapituloActionPerformed(evt);
            }
        });
        jPanel2.add(jbPassarCapitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 10, 50, 30));

        jbVoltarCapitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/biblia/imagens/left-arrow.png"))); // NOI18N
        jbVoltarCapitulo.setToolTipText("");
        jbVoltarCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarCapituloActionPerformed(evt);
            }
        });
        jPanel2.add(jbVoltarCapitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        TelaEscolherCapitulo tela = new TelaEscolherCapitulo(livro-1);
        tela.setVisible(true);
        tela.setLocationRelativeTo(this);
        
    }//GEN-LAST:event_formWindowClosing

    private void jbPassarCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPassarCapituloActionPerformed
        aumentarCapítulo();
        
    }//GEN-LAST:event_jbPassarCapituloActionPerformed

    private void jbVoltarCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarCapituloActionPerformed
        diminuirCapítulo();
    }//GEN-LAST:event_jbVoltarCapituloActionPerformed

    public void carregarCapitulo(int capitulo) {
        try {
            List<String> vers = dao.consultarVersosDoCapítulo(livro, capitulo);

            String texto = "";

            int contador = 0;

            for (String v : vers) {
                texto += "<p>" + (contador+1) + ". " + v + "</p>";
                contador++;
            }

            getPreferredSize("<html>"+texto+"</html>", true, 420);

            jPanel2.setPreferredSize(new Dimension(440, versiculos.getPreferredSize().height + 80));
        } catch (SQLException ex) {
            System.out.println("Não deu!");
            ex.printStackTrace();
        }        
    }
    
    public void aumentarCapítulo(){
        capitulo++;
        System.out.println("Capitulo agora é " + capitulo);
        if (capitulo > qtdCap[livro - 1]){
            livro++;
            capitulo = 1;
        }

        try {
            jlLivro.setText(dao.consultarLivro(livro));
            jlCapitulo.setText(""+capitulo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

        carregarCapitulo(capitulo);
    }
        
    public void diminuirCapítulo(){
        capitulo--;
        
        if (capitulo < 1){
            livro--;
            capitulo = qtdCap[livro - 1];
        }

        try {
            jlLivro.setText(dao.consultarLivro(livro));
            jlCapitulo.setText(""+capitulo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

        carregarCapitulo(capitulo);
    }
    
    // https://blog.nobel-joergensen.com/2009/01/18/changing-preferred-size-of-a-html-jlabel/
    public Dimension getPreferredSize(String html, boolean width, int prefSize) {
 
        versiculos.setText(html);
 
        View view = (View) versiculos.getClientProperty(
                javax.swing.plaf.basic.BasicHTML.propertyKey);
 
        view.setSize(width?prefSize:0,width?0:prefSize);
 
        float w = view.getPreferredSpan(View.X_AXIS);
        float h = view.getPreferredSpan(View.Y_AXIS);
 
        return new Dimension((int) Math.ceil(w),
                (int) Math.ceil(h));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbPassarCapitulo;
    private javax.swing.JButton jbVoltarCapitulo;
    private javax.swing.JLabel jlCapitulo;
    private javax.swing.JLabel jlLivro;
    private javax.swing.JLabel versiculos;
    // End of variables declaration//GEN-END:variables
}
