/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.calculadora.telas;

import br.edu.calculadora.CalculadoraNormal;
import br.edu.desktop.tela.Desktop;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class TelaCalculadora extends javax.swing.JFrame {

    private CalculadoraNormal calculadoraNormal;

    public CalculadoraNormal getCalculadoraNormal() {
        return calculadoraNormal;
    }

    public void setCalculadoraNormal(CalculadoraNormal calcNormal) {
        calculadoraNormal = calcNormal;
    }

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
        
        setCalculadoraNormal(new CalculadoraNormal());

        calculadoraNormal.setTelaCalculadora(this);
        calculadoraNormal.setDisplay(inputCalculator);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CalculadoraMenu = new javax.swing.JTabbedPane();
        TelaNormal = new javax.swing.JPanel();
        inputCalculator = new javax.swing.JTextField();
        btnDEL = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btnPerc = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnMais = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnPonto = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        TelaIMC = new javax.swing.JPanel();
        AlturamjLabel = new javax.swing.JLabel();
        alturamjTextField = new javax.swing.JTextField();
        PesokgjLabel = new javax.swing.JLabel();
        pesokgjTextField = new javax.swing.JTextField();
        IMCjLabel = new javax.swing.JLabel();
        imcjTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        calcularimcjButton = new javax.swing.JButton();
        limparjButton2 = new javax.swing.JButton();
        faixapesojLabel = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        btnSobre = new javax.swing.JMenu();
        btnAjuda = new javax.swing.JMenu();
        btnHistorico = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TelaNormal.setBackground(new java.awt.Color(255, 255, 255));
        TelaNormal.setOpaque(false);
        TelaNormal.setPreferredSize(new java.awt.Dimension(400, 450));

        inputCalculator.setEditable(false);
        inputCalculator.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        inputCalculator.setForeground(new java.awt.Color(255, 255, 255));
        inputCalculator.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputCalculator.setText("0");

        btnDEL.setBackground(new java.awt.Color(51, 51, 51));
        btnDEL.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDEL.setForeground(new java.awt.Color(255, 255, 255));
        btnDEL.setText("DEL");
        btnDEL.setBorder(null);
        btnDEL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELActionPerformed(evt);
            }
        });

        btnAC.setBackground(new java.awt.Color(51, 51, 51));
        btnAC.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAC.setForeground(new java.awt.Color(255, 255, 255));
        btnAC.setText("AC");
        btnAC.setBorder(null);
        btnAC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        btnPerc.setBackground(new java.awt.Color(51, 51, 51));
        btnPerc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnPerc.setForeground(new java.awt.Color(255, 255, 255));
        btnPerc.setText("%");
        btnPerc.setBorder(null);
        btnPerc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercActionPerformed(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(51, 51, 51));
        btnDiv.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(255, 255, 255));
        btnDiv.setText("÷");
        btnDiv.setBorder(null);
        btnDiv.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(51, 51, 51));
        btn7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setBorder(null);
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(51, 51, 51));
        btn8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setBorder(null);
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(51, 51, 51));
        btn9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setBorder(null);
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnMenos.setBackground(new java.awt.Color(51, 51, 51));
        btnMenos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMenos.setForeground(new java.awt.Color(255, 255, 255));
        btnMenos.setText("-");
        btnMenos.setBorder(null);
        btnMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(51, 51, 51));
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setBorder(null);
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btnMais.setBackground(new java.awt.Color(51, 51, 51));
        btnMais.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMais.setForeground(new java.awt.Color(255, 255, 255));
        btnMais.setText("+");
        btnMais.setBorder(null);
        btnMais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(51, 51, 51));
        btn5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setBorder(null);
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(51, 51, 51));
        btn6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setBorder(null);
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(51, 51, 51));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setBorder(null);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(51, 51, 51));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setBorder(null);
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(51, 51, 51));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setBorder(null);
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(51, 51, 51));
        btn0.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setBorder(null);
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(102, 102, 102));
        btnIgual.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(255, 255, 255));
        btnIgual.setText("=");
        btnIgual.setBorder(null);
        btnIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnPonto.setBackground(new java.awt.Color(51, 51, 51));
        btnPonto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnPonto.setForeground(new java.awt.Color(255, 255, 255));
        btnPonto.setText(",");
        btnPonto.setBorder(null);
        btnPonto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPontoActionPerformed(evt);
            }
        });

        btnMulti.setBackground(new java.awt.Color(51, 51, 51));
        btnMulti.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMulti.setForeground(new java.awt.Color(255, 255, 255));
        btnMulti.setText("×");
        btnMulti.setBorder(null);
        btnMulti.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaNormalLayout = new javax.swing.GroupLayout(TelaNormal);
        TelaNormal.setLayout(TelaNormalLayout);
        TelaNormalLayout.setHorizontalGroup(
            TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputCalculator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(TelaNormalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(TelaNormalLayout.createSequentialGroup()
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaNormalLayout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TelaNormalLayout.createSequentialGroup()
                                .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(TelaNormalLayout.createSequentialGroup()
                        .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TelaNormalLayout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaNormalLayout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TelaNormalLayout.setVerticalGroup(
            TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaNormalLayout.createSequentialGroup()
                .addComponent(inputCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TelaNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnDEL.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnAC.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnPerc.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnDiv.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn7.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn8.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn9.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnMenos.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn4.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnMais.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn5.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn6.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn1.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn2.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn3.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btn0.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnIgual.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnPonto.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        btnMulti.putClientProperty(FlatClientProperties.STYLE, "arc: 12");

        CalculadoraMenu.addTab("Calculadora Normal", TelaNormal);

        TelaIMC.setForeground(new java.awt.Color(255, 255, 255));
        TelaIMC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TelaIMC.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                TelaIMCComponentShown(evt);
            }
        });

        AlturamjLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        AlturamjLabel.setForeground(new java.awt.Color(255, 255, 255));
        AlturamjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AlturamjLabel.setText("Altura(m)");

        alturamjTextField.setBackground(new java.awt.Color(0, 0, 0));
        alturamjTextField.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        alturamjTextField.setForeground(new java.awt.Color(255, 255, 255));
        alturamjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alturamjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturamjTextFieldActionPerformed(evt);
            }
        });

        PesokgjLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        PesokgjLabel.setForeground(new java.awt.Color(255, 255, 255));
        PesokgjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PesokgjLabel.setText("Peso(kg)");

        pesokgjTextField.setBackground(new java.awt.Color(0, 0, 0));
        pesokgjTextField.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        pesokgjTextField.setForeground(new java.awt.Color(255, 255, 255));
        pesokgjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pesokgjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesokgjTextFieldActionPerformed(evt);
            }
        });

        IMCjLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        IMCjLabel.setForeground(new java.awt.Color(255, 255, 255));
        IMCjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IMCjLabel.setText("IMC");

        imcjTextField.setEditable(false);
        imcjTextField.setBackground(new java.awt.Color(0, 0, 0));
        imcjTextField.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        imcjTextField.setForeground(new java.awt.Color(255, 255, 255));
        imcjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        imcjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imcjTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><p style=\"text-align: center;\">Informe a altura em metros e o seu peso quilogramas(kg)</p></html>");

        calcularimcjButton.setBackground(new java.awt.Color(51, 51, 51));
        calcularimcjButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        calcularimcjButton.setForeground(new java.awt.Color(255, 255, 255));
        calcularimcjButton.setText("Calcular IMC");
        calcularimcjButton.setBorder(null);
        calcularimcjButton.setBorderPainted(false);
        calcularimcjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        calcularimcjButton.setSelected(true);
        calcularimcjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularimcjButtonActionPerformed(evt);
            }
        });

        limparjButton2.setBackground(new java.awt.Color(51, 51, 51));
        limparjButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        limparjButton2.setForeground(new java.awt.Color(255, 255, 255));
        limparjButton2.setText("Limpar");
        limparjButton2.setBorder(null);
        limparjButton2.setBorderPainted(false);
        limparjButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        limparjButton2.setPreferredSize(new java.awt.Dimension(78, 19));
        limparjButton2.setSelected(true);
        limparjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparjButton2ActionPerformed(evt);
            }
        });

        faixapesojLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        faixapesojLabel.setForeground(new java.awt.Color(255, 255, 255));
        faixapesojLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout TelaIMCLayout = new javax.swing.GroupLayout(TelaIMC);
        TelaIMC.setLayout(TelaIMCLayout);
        TelaIMCLayout.setHorizontalGroup(
            TelaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaIMCLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(TelaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(faixapesojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TelaIMCLayout.createSequentialGroup()
                        .addComponent(calcularimcjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limparjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(TelaIMCLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(TelaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaIMCLayout.createSequentialGroup()
                        .addGroup(TelaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PesokgjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlturamjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TelaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alturamjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesokgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TelaIMCLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(IMCjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(imcjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TelaIMCLayout.setVerticalGroup(
            TelaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaIMCLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlturamjLabel)
                    .addComponent(alturamjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(TelaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesokgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesokgjLabel))
                .addGap(32, 32, 32)
                .addGroup(TelaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaIMCLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(IMCjLabel))
                    .addComponent(imcjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(faixapesojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TelaIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limparjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcularimcjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        alturamjTextField.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        pesokgjTextField.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        imcjTextField.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        calcularimcjButton.putClientProperty(FlatClientProperties.STYLE, "arc: 12");
        limparjButton2.putClientProperty(FlatClientProperties.STYLE, "arc: 12");

        CalculadoraMenu.addTab("Calculadora IMC", TelaIMC);

        btnSobre.setText("Sobre");
        btnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSobreMouseClicked(evt);
            }
        });
        MenuBar.add(btnSobre);

        btnAjuda.setText("Ajuda");
        btnAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjudaMouseClicked(evt);
            }
        });
        MenuBar.add(btnAjuda);

        btnHistorico.setText("Histórico");
        btnHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoricoMouseClicked(evt);
            }
        });
        MenuBar.add(btnHistorico);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CalculadoraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CalculadoraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setEnabledIfDivZero(Boolean value) {
        btnPerc.setEnabled(value);
        btnMais.setEnabled(value);
        btnMulti.setEnabled(value);
        btnDiv.setEnabled(value);
        btnMenos.setEnabled(value);
        btnMais.setEnabled(value);
        btnPonto.setEnabled(value);
    }

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        calculadoraNormal.onClickOperator(evt);
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPontoActionPerformed
        calculadoraNormal.onClickPoint(evt);
    }//GEN-LAST:event_btnPontoActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        calculadoraNormal.onClickResult(evt);
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        calculadoraNormal.onClickNumber(evt);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        calculadoraNormal.onClickNumber(evt);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        calculadoraNormal.onClickNumber(evt);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        calculadoraNormal.onClickNumber(evt);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        calculadoraNormal.onClickNumber(evt);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        calculadoraNormal.onClickNumber(evt);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisActionPerformed
        calculadoraNormal.onClickOperator(evt);
    }//GEN-LAST:event_btnMaisActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        calculadoraNormal.onClickNumber(evt);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        calculadoraNormal.onClickOperator(evt);
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        calculadoraNormal.onClickNumber(evt);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        calculadoraNormal.onClickNumber(evt);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        calculadoraNormal.onClickNumber(evt);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        calculadoraNormal.onClickOperator(evt);
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercActionPerformed
        calculadoraNormal.onClickOperator(evt);
    }//GEN-LAST:event_btnPercActionPerformed

    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        calculadoraNormal.onClickAC();
    }//GEN-LAST:event_btnACActionPerformed

    private void btnDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELActionPerformed
        calculadoraNormal.onClickDelete();
    }//GEN-LAST:event_btnDELActionPerformed

    private void btnHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoricoMouseClicked
        TelaHistorico telaHistorico = new TelaHistorico(this, true, calculadoraNormal.getHistory());
        telaHistorico.setVisible(true);
    }//GEN-LAST:event_btnHistoricoMouseClicked

    private void btnAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjudaMouseClicked
        TelaAjuda telaAjuda = new TelaAjuda(this, true);
        telaAjuda.setVisible(true);
    }//GEN-LAST:event_btnAjudaMouseClicked

    private void btnSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMouseClicked
        TelaSobre telaSobre = new TelaSobre(this, true);
        telaSobre.setVisible(true);
    }//GEN-LAST:event_btnSobreMouseClicked

    private void alturamjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturamjTextFieldActionPerformed

    }//GEN-LAST:event_alturamjTextFieldActionPerformed

    private void pesokgjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesokgjTextFieldActionPerformed

    }//GEN-LAST:event_pesokgjTextFieldActionPerformed

    private void imcjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imcjTextFieldActionPerformed

    }//GEN-LAST:event_imcjTextFieldActionPerformed

    private void calcularimcjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularimcjButtonActionPerformed
        String pesoKgStr = pesokgjTextField.getText();
        String alturaMStr = alturamjTextField.getText();

        if (pesoKgStr.length() > 0 && alturaMStr.length() > 0) {
            limparjButton2.setEnabled(true);
            String FaixaPeso = "0";

            try {
                double AlturaM = Double.parseDouble(alturaMStr.replaceAll(",", "."));
                double PesoKG = Double.parseDouble(pesoKgStr);
                double Imc;

                Imc = PesoKG / (Math.pow(AlturaM, 2));
                imcjTextField.setText(String.format("%.2f", Imc));

                if (Imc < 16) {
                    FaixaPeso = "Magreza grave";
                } else if (Imc >= 16 && Imc <= 16.9) {
                    FaixaPeso = "Magreza moderada";
                } else if (Imc >= 17 && Imc <= 18.5) {
                    FaixaPeso = "Magreza leve";
                } else if (Imc >= 18.6 && Imc <= 24.9) {
                    FaixaPeso = "Peso ideal";
                } else if (Imc >= 25 && Imc <= 29.9) {
                    FaixaPeso = "Sobrepeso";
                } else if (Imc >= 30 && Imc <= 34.9) {
                    FaixaPeso = "Obesidade grau I";
                } else if (Imc >= 35 && Imc <= 39.9) {
                    FaixaPeso = "Obesidade grau II ou severa";
                } else if (Imc > 40) {
                    FaixaPeso = "Obesidade grau III ou mórbida";
                }

                faixapesojLabel.setText("Sua faixa de peso: " + FaixaPeso);
                String historyAdd = "IMC: " + String.format("%.2f", Imc) + " - " + FaixaPeso + " - Altura: " + AlturaM + " - Peso: " + PesoKG;
                ArrayList<String> history = calculadoraNormal.getHistory();
                history.add("<html><b style=\"font-size: 9px\">" + historyAdd + "</b></html>");
                calculadoraNormal.setHistory(history);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro! Utilize apenas números.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Insira os valores requeridos!");
        }
    }//GEN-LAST:event_calcularimcjButtonActionPerformed

    private void limparjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparjButton2ActionPerformed
        pesokgjTextField.setText("");
        alturamjTextField.setText("");
        imcjTextField.setText("");
        faixapesojLabel.setText("");
        limparjButton2.setEnabled(false);

    }//GEN-LAST:event_limparjButton2ActionPerformed

    private void TelaIMCComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TelaIMCComponentShown
        String pesoKgStr = pesokgjTextField.getText();
        String alturaMStr = alturamjTextField.getText();
        if (pesoKgStr.length() > 0 || alturaMStr.length() > 0) {
            limparjButton2.setEnabled(true);
        } else {
            limparjButton2.setEnabled(false);
        }
    }//GEN-LAST:event_TelaIMCComponentShown

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Desktop().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        FlatMacDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCalculadora telaCalculadora = new TelaCalculadora();
                telaCalculadora.setVisible(true);

                telaCalculadora.setCalculadoraNormal(new CalculadoraNormal());
                CalculadoraNormal calculadoraNormal = telaCalculadora.getCalculadoraNormal();

                calculadoraNormal.setTelaCalculadora(telaCalculadora);
                calculadoraNormal.setDisplay(telaCalculadora.inputCalculator);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlturamjLabel;
    private javax.swing.JTabbedPane CalculadoraMenu;
    private javax.swing.JLabel IMCjLabel;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel PesokgjLabel;
    private javax.swing.JPanel TelaIMC;
    private javax.swing.JPanel TelaNormal;
    private javax.swing.JTextField alturamjTextField;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAC;
    private javax.swing.JMenu btnAjuda;
    private javax.swing.JButton btnDEL;
    private javax.swing.JButton btnDiv;
    private javax.swing.JMenu btnHistorico;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMais;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnPerc;
    private javax.swing.JButton btnPonto;
    private javax.swing.JMenu btnSobre;
    private javax.swing.JButton calcularimcjButton;
    private javax.swing.JLabel faixapesojLabel;
    private javax.swing.JTextField imcjTextField;
    public javax.swing.JTextField inputCalculator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton limparjButton2;
    private javax.swing.JTextField pesokgjTextField;
    // End of variables declaration//GEN-END:variables
}
